Peakfijn/Conventions

packages/commit-types-peakfijn/index.json
When you create a new release with semantic releases it creates a `chore` type commit. This commit includes all changes required for pushing a new version. But because `chore` also triggers a new patch version, this can be "looped". When someone creates a new release, and accidentally reruns the script, it will create yet another release.
=> feature(commit-types): add release as new type

lerna.json
This changes the message Lerna adds to new releases. It's nothing significant but merely a bit more semantic change.
=> Use new release commit type

packages/commit-types-peakfijn/package.json, packages/commitlint-config-peakfijn/package.json, packages/conventional-changelog-peakfijn/package.json, packages/cz-changelog-peakfijn/package.json, packages/release-rules-peakfijn/package.json
When opening the repository or homepage URL from NPM, all packages are linking to the root. This feels a bit weird because you selected a specific version. Instead, the package should link to its dedicated readme page.
=> Use proper homepage url

.commitlintrc.yml, @peakfijn/config-release-expo/index.js, @peakfijn/config-release-expo/package.json, greenkeeper.json, lerna.json
This introduces the first draft of the Semantic Release configuration for Expo releases. It assumes you have manifests for `test`, `staging` and `production`. Other than that, it's pretty straightforward. It also groups a couple of packages so we won't have to litter the project dependency list.
=> Shareable Semantic Release Expo configuration

packages/release-rules-peakfijn/index.js
Without this breaking changes are not handled as breaking changes. This makes sure both breaking and revert commits are handled properly.
=> fix(release-rules): include default breaking and revert rules

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/PULL_REQUEST_TEMPLATE.md
It will not only help "outsiders", but also (new) interns breaking information up into separate small and easy questions.
=> documentation: add helpful github templates for issues and pull requests

@peakfijn/config-release-expo/README.md
Use the same read me format as all (new) others.
=> documentation(config-release-expo): use the new uniform readme format

.commitlintrc.yml, @peakfijn/config-commitlint/README.md, @peakfijn/config-commitlint/index.js, @peakfijn/config-commitlint/package.json, greenkeeper.json
This allows us to "implement" commitlint using only `npm install --save-dev @peakfijn/commitlint` and the `package.json` configuration.
=> feature(config-commitlint): add first draft of commitlint config

.commitlintrc.yml, @peakfijn/config-commitizen/README.md, @peakfijn/config-commitizen/index.js, @peakfijn/config-commitizen/package.json, greenkeeper.json
This allows us to "implement" commitizen using only `npm install --save-dev @peakfijn/commitizen` and the `package.json` configuration.
=> feature(config-commitizen): add first draft of commitizen config

packages/cz-changelog-peakfijn/index.js
[Double space in the beginning of commit message doesn't pass commit linters but passed Commitizen](https://github.com/Peakfijn/Conventions/issues/40)
The way I 'fixed' this, is by trimming the subject (I additionally also trimmed the footer) so that even when you add a additional space or subject in the beginning of those entities, they'll be trimmed away before you even commit.
=> fix(commitizen): space in the beginning of subject is causing commitlint to fail

@peakfijn/config-stylelint/bin/stylelint
Fixes the binary proxy issue once and for all. It adds support for both approaches, depending on the node version etc.
=> fix(stylelint): add support for both approaches to stylelint binaries

@peakfijn/config-release-expo/package.json
=> refactor: upgrade semantic-release-expo to version 2.1.2

packages/conventional-changelog-peakfijn/package.json
=> refactor: upgrade ava to version 1.2.0

packages/commitlint-config-peakfijn/index.js, packages/commitlint-config-peakfijn/index.test.js
There were some valid comments about the length of the subject. The value `20` came from the original `header-min-length` rule. But this is now changed to `subject-*` only because of the big differences in commit type. I think this will be a welcome change for some people.
=> refactor(commitlint): lower minimum length of subject to `15`

.travis.yml
Currently, NPM uses an old node-gyp version which includes this issue. Backporting the fix into tar or node-gyp is proven to be difficult. They are working on it though!
=> pipeline: temporary disable audit-block awaiting tar/node-gyp fix

@peakfijn/config-stylelint/package.json
Upgrades resolve pkg to the latest version in stylelint, a manual upgrade to enable greenkeeper again.
=> refactor(stylelint): upgrade resolve-pkg to version 2.0.0

@peakfijn/config-stylelint/package.json
Upgrades stylelint to the latest version in stylelint, a manual upgrade to enable greenkeeper again.
=> refactor(stylelint): upgrade stylelint to version 10.0.1

@peakfijn/config-commitlint/package.json
Upgrades resolve pkg to the latest version in commitlint, a manual upgrade to enable greenkeeper again.
=> refactor(commitlint): upgrade resolve-pkg to version 2.0.0

@peakfijn/config-eslint-expo/package.json
Upgrades babel eslint to the latest version in eslint, a manual upgrade to enable greenkeeper again.
=> refactor(eslint): upgrade babel-eslint to version 10.0.1

@peakfijn/config-commitizen/package.json
Upgrades resolve pkg to the latest version in commitizen, a manual upgrade to enable greenkeeper again.
=> refactor(commitizen): upgrade resolve-pkg to version 2.0.0

@peakfijn/config-release-expo/package.json, @peakfijn/config-release-laravel/package.json, @peakfijn/config-release-react/package.json, @peakfijn/config-release/package.json
Upgrades resolve pkg to the latest version in semantic release, a manual upgrade to enable greenkeeper again.
=> refactor(semantic-release): upgrade resolve-pkg to version 2.0.0

package.json
At least the repository url is required for the changelogs, else it might pick the wrong url again.
=> chore: add missing repository and bugs url to package file

commitlint.config.js, package.json
This should exclude future commits by greenkeeper, updating lock files. Because this is an automated process and not-configurable, this should not be linted on.
=> refactor: exclude package lock updates by greenkeeper from commitlint
