Peakfijn/Conventions

greenkeeper.json
This package was missing in the Greenkeeper configuration, so lets add it.
=> Fix greenkeeper

.commitlintrc.yml, @peakfijn/config-release-laravel/index.js, @peakfijn/config-release-laravel/package.json, greenkeeper.json, lerna.json
Same thing like the [Expo package](#8), but for Laravel.
=> Shareable Semantic Release Laravel configuration

@peakfijn/config-release-laravel/README.md
Use the same read me format as all (new) others.
=> documentation(config-release-laravel): use the new uniform readme format

.commitlintrc.yml, @peakfijn/config-release-react/README.md, @peakfijn/config-release-react/index.js, @peakfijn/config-release-react/package.json
=> Sharable Semantic Release React config

@peakfijn/config-release-expo/package.json
=> refactor(config-release-expo): upgrade dependencies to latest version

greenkeeper.json
=> fix: greenkeeper configuration and group by subject

@peakfijn/config-stylelint/bin/stylelint
Fixes in issue encountered in one of our Pipelines.
=> fix(stylelint): proxy binary reference in original manifest

.gitignore, .npmrc, .travis.yml, @peakfijn/config-commitizen/package-lock.json, @peakfijn/config-commitlint/package-lock.json, @peakfijn/config-eslint-expo/package-lock.json, @peakfijn/config-eslint/package-lock.json, @peakfijn/config-release-expo/package-lock.json, @peakfijn/config-release-laravel/package-lock.json, @peakfijn/config-release-react/package-lock.json, @peakfijn/config-release/package-lock.json, @peakfijn/config-stylelint/package-lock.json, package-lock.json, package.json, packages/commit-types-peakfijn/package-lock.json, packages/commitlint-config-peakfijn/package-lock.json, packages/conventional-changelog-peakfijn/package-lock.json, packages/cz-changelog-peakfijn/package-lock.json, packages/eslint-config-peakfijn-expo/package-lock.json, packages/eslint-config-peakfijn/package-lock.json, packages/release-rules-peakfijn/package-lock.json, packages/stylelint-config-peakfijn/package-lock.json
Part of first stable release `1.0.0`. This should speed up the pipelines and reinstalls, using the power of ci.
=> Re-enable lockfiles

@peakfijn/config-stylelint/package.json, packages/stylelint-config-peakfijn/package.json
=> Greenkeeper/stylelint/ava 1.2.0

@peakfijn/config-release-expo/package.json, @peakfijn/config-release-laravel/package.json, @peakfijn/config-release-react/package.json, @peakfijn/config-release/package.json, packages/conventional-changelog-peakfijn/package.json, packages/release-rules-peakfijn/package.json
=> Greenkeeper/semantic release/ava 1.2.0

@peakfijn/config-commitizen/package.json, packages/cz-changelog-peakfijn/package.json
=> Greenkeeper/commitizen/ava 1.2.0

@peakfijn/config-commitlint/package.json, packages/commit-types-peakfijn/package.json, packages/commitlint-config-peakfijn/package.json
=> Greenkeeper/commitlint/ava 1.2.0

@peakfijn/config-commitlint/package.json
=> refactor: upgrade commitlint to version 7.4.0

@peakfijn/config-eslint-expo/package.json, packages/eslint-config-peakfijn-expo/package.json
=> Greenkeeper/eslint/eslint import resolver babel module 5.0.1

@peakfijn/config-eslint-expo/package.json, @peakfijn/config-eslint/package.json
=> Greenkeeper/eslint/eslint plugin jsx a11y 6.2.0

@peakfijn/config-eslint-expo/package.json, @peakfijn/config-eslint/package.json, packages/eslint-config-peakfijn-expo/package.json, packages/eslint-config-peakfijn/package.json
=> Greenkeeper/eslint/ava 1.2.0

package.json
=> refactor: upgrade @commitlint/cli to version 7.3.2

packages/cz-changelog-peakfijn/package.json
=> refactor: upgrade @commitlint/lint to version 7.4.0

@peakfijn/config-eslint-expo/package.json, @peakfijn/config-eslint/package.json
=> Greenkeeper/eslint/eslint plugin import 2.16.0

packages/cz-changelog-peakfijn/README.md
=> docs: correct typo

@peakfijn/config-eslint-expo/package.json, @peakfijn/config-eslint/package.json
Upgrades resolve pkg to the latest version in eslint, a manual upgrade to enable greenkeeper again.
=> refactor(eslint): upgrade resolve-pkg to version 2.0.0

packages/commitlint-config-peakfijn/package-lock.json, packages/commitlint-config-peakfijn/package.json
=> Greenkeeper/commitlint/@commitlint/config conventional 7.6.0

@peakfijn/config-eslint-expo/package-lock.json, @peakfijn/config-eslint-expo/package.json, @peakfijn/config-eslint/package-lock.json, @peakfijn/config-eslint/package.json, packages/eslint-config-peakfijn/package-lock.json, packages/eslint-config-peakfijn/package.json
=> Greenkeeper/eslint/eslint plugin jsdoc 5.0.2

@peakfijn/config-commitizen/package-lock.json, @peakfijn/config-commitizen/package.json, @peakfijn/config-commitlint/package-lock.json, @peakfijn/config-commitlint/package.json, packages/cz-changelog-peakfijn/package-lock.json, packages/cz-changelog-peakfijn/package.json
#173 
Provide the issue(s) which this pull request relates to or fixes.
Are there things the maintainers should be aware of before merging or closing this pull request?
=> fix: prototype pollution in commitlint packages

.travis.yml
This shouldn't be an issue anymore after the **big upgrade**(tm)
=> pipeline: enable audit step in install again
